// ========== Recipe Data (from design images) ==========
const recipes = {
    'Toshkent oshi': {
        ingredients: [
            { name: 'Guruch', amount: '1 kg' },
            { name: "Go'sht", amount: '800 gr - 1 kg' },
            { name: 'Sabzi', amount: '1-1.2 kg' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: "Yog'", amount: '250-300 ml' },
            { name: 'Dumba', amount: '100 gr' },
            { name: "No'xat", amount: '100-150 gr' },
            { name: 'Mayiz', amount: '50 gr' },
            { name: 'Zira, tuz, murch va azoq zirk (barbaris)', amount: '' },
            { name: "Suv: Qaynoq suv (guruchni yopishi uchun)", amount: '' },
        ],
        steps: [
            "Zirvakni tayyorlash: Qozonda yog'ni qizdirib, avval piyozni och tillarang bo'lguncha qovuring. Keyin go'shtni solib, uning sirti qizarguncha qovurishda davom eting.",
            "Sabzi va no'xat: Sabzini solib, biroz yumshaguncha qovuring. So'ngra mahsulotlar ko'rilguncha suv quyib, isitilgan no'xatni qo'shing. Zirvakni past olovda taxminan 40-50 daqiqa qaynatib.",
            "Mayiz va ziravotlar: Pishishiga 15 daqiqa qolganda mayiz va ziravotlarni qo'shing.",
            "Guruch solish: Yuvilgan guruchni zirvak ustiga tekis yoyib soling. Guruch ustidan taxminan 1-1.5 sm balandlikda qaynoq suv quying.",
            "Damlash: Guruch suvni to'liq shimib bo'lgach, olovni eng pastga pasaytirib, qozonni 20-25 daqiqaga damlab qo'ying.",
            "Toshkent oshi odatda go'shti ustiga qo'yib, qazi, kashnich va murch bilan bezatilgan holda tortiladi.",
        ],
    },
    'Andijon oshi': {
        ingredients: [
            { name: 'Guruch (Devzira)', amount: '1 kg' },
            { name: "Go'sht", amount: '1 kg' },
            { name: 'Sabzi', amount: '1 kg' },
            { name: 'Piyoz', amount: '2-3 dona' },
            { name: "Yog'", amount: '300 ml' },
            { name: 'Zira, tuz', amount: "Ta'bga ko'ra" },
            { name: 'Sarimsoqpiyoz', amount: "Xohishga ko'ra" },
        ],
        steps: [
            "Guruchni tayyorlash: Devzira guruchini yaxshilab yuvib, iliq va tuzli suvda kamida 1-2 soat ivitib qo'ying.",
            "Yog'ni dog'lash: Qozonda yog'ni yaxshilab qizdiring. Agar paxta yog'i bo'lsa, oq tutun chiqquncha dog'lang.",
            "Go'sht va piyozni qovurish: Go'shtni yirikroq bo'laklarga bo'lib, tillarang bo'lguncha qovuring. Keyin to'g'ralgan piyozni qo'shib, u ham qizarguncha davom eting.",
            "Sabzi solish: To'g'ralgan sabzini qo'shing va biroz yumshaguncha qovuring. So'ngra masalliqlar ko'milguncha suv quyib, past olovda 40-50 daqiqa davomida zirvak qaynating.",
            "Guruch solish: Ivigan guruchni zirvak ustiga tekis qilib yoying. Guruch ustidan taxminan 1-1,5 sm balandlikda qaynoq suv quying.",
            "Pishirish: Olovni balandlatib, suv butunlay tortiguncha kuting. Guruchni chetlaridan o'rtaga to'plab, o'rtasidan teshiklar oching.",
            "Damlash: Suvi to'liq tortigach, qozon qopqog'ini mahkam yopib, olovni eng past darajaga tushiring va 20-25 daqiqa dam bering.",
        ],
    },
    'Dimlama': {
        ingredients: [
            { name: "Go'sht", amount: '1 kg' },
            { name: "Dumba yog'i", amount: '100 gr' },
            { name: 'Piyoz', amount: '3-4 dona' },
            { name: 'Sabzi', amount: '3-4 dona' },
            { name: 'Kartoshka', amount: '6-8 dona' },
            { name: "Pomidor va bulg'or qalampir", amount: '2-3 dona' },
            { name: 'Karam', amount: 'Yarimta' },
            { name: "Tuz, zira, kashnich urug'i, murch", amount: '' },
        ],
        steps: [
            "Go'shtni joylash: Sovuq qozon tubiga avval dumba yog'ini, so'ngra go'shtni terib chiqing. Tuz va ziravorlar seping.",
            "Sabzavotlarni qatlamlash: Go'sht ustidan piyozni, so'ngra sabzi, pomidor va bulg'or qalampirni qavatma-qavat tering.",
            "Kartoshka va ko'katlar: Eng ustki qismga butun kartoshkalarni va ko'katlar bog'lamini qo'ying.",
            "Karam bilan yopish: Hammasining ustini karam barglari bilan mahkam yopib chiqing.",
            "Dimlash: Qozon qopqog'ini mahkam yoping. Avval 10-15 daqiqa o'rtacha olovda, so'ngra eng past olovda 1,5-2 soat davomida dimlang.",
        ],
    },
    'Qazon Kabob': {
        ingredients: [
            { name: "Go'sht", amount: '1 kg' },
            { name: 'Kartoshka', amount: '1 kg' },
            { name: "Yog'", amount: '300 ml' },
            { name: "Tuz, zira, murch, kashnich urug'i", amount: '' },
            { name: 'Piyoz: Taom ustiga sepish uchun', amount: '' },
        ],
        steps: [
            "Go'shtni marinadlash: Go'sht bo'laklariga tuz va hamma ziravorlarni surtib, kamida 30 daqiqa tindirib qo'ying.",
            "Kartoshkani qovurish: Qozonda yog'ni yaxshi qizdiring. Tozalangan butun kartoshkalarni tilla rang bo'lguncha baland olovda qovurib oling.",
            "Go'shtni qovurish: Xuddi shu yog'da go'sht bo'laklarini solib, har tomonini qizarguncha baland olovda qovuring.",
            "Joylashtirish: Go'shtlarni qozon devoriga tering, ustidan qovurilgan kartoshkalarni qo'ying.",
            "Dimlash: Yarim piyola suv quyib, qozon qopqog'ini jips yoping. Olovni eng pastga qo'yib, 45-60 daqiqa dimlang.",
            "Dasturxonga tortishda kartoshkalarni chetiga, go'shtni o'rtaga qo'yib, ustidan to'g'ralgan yangi piyoz seping.",
        ],
    },
    'Qovurdoq': {
        ingredients: [
            { name: "Go'sht", amount: '1 kg' },
            { name: 'Kartoshka', amount: '1 kg' },
            { name: 'Piyoz', amount: '2-3 dona' },
            { name: "Yog'", amount: '200 ml' },
            { name: 'Tuz, murch, zira', amount: "Ta'bga ko'ra" },
            { name: 'Suv', amount: 'yarim stakan' },
        ],
        steps: [
            "Go'shtni qovurish: Qozonda yog'ni qizdirib, go'shtni soling. Go'sht suvi chiqib, chetlari qizarguncha baland olovda qovuring.",
            "Piyozni qo'shish: Ustiga piyozni solib, piyoz tilla rangga kirguncha qovurishda davom eting.",
            "Kartoshkani solish: To'g'ralgan kartoshkalarni qo'shing. Hammasini birga 10-15 daqiqa kartoshkalar qizarguncha qovuring.",
            "Ziravorlash: Tuz, murch va ziravorlarni seping.",
            "Dimlash: Yarim stakan suv quyib, qozon qopqog'ini yoping. Olovni pasaytirib, 30-40 daqiqa pishiring.",
        ],
    },
    'Norin': {
        ingredients: [
            { name: "Go'sht", amount: '1 kg' },
            { name: 'Qazi', amount: "Xohishga ko'ra" },
            { name: 'Un', amount: '1 kg' },
            { name: 'Tuxum', amount: '1-2 dona' },
            { name: 'Suv', amount: '1,5 stakan' },
            { name: "O'simlik yog'i", amount: 'Xamir uchun' },
            { name: "Zira, tuz, qora murch", amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Go'shtni pishirish: Go'sht va qazini sovuq suvga solib, 2-3 soat davomida past olovda qaynating.",
            "Xamir tayyorlash: Un, tuxum, tuz va suvdan qattiq xamir qoring. 30 daqiqa tindirib, juda yupqa qilib yoying.",
            "Xamirni pishirish: Yoyilgan xamirni yirik bo'laklarga bo'lib, go'sht pishgan sho'rvada 2-3 daqiqa qaynatib oling.",
            "Moylash: Pishgan xamir bo'laklarini olib, yoyib sovuting va har bir qavatini yog' bilan moylang.",
            "To'g'rash: Xamirni ustma-ust taxlab, juda ingichka shaklida to'g'rang. Go'sht va qazini ham ingichka somoncha shaklida to'g'rang.",
            "Aralashtirish: To'g'ralgan xamir va go'shtni katta idishga solib, murch va zira qo'shib aralashtiring.",
        ],
    },
    'Bifshteks': {
        ingredients: [
            { name: "Go'sht (qiyma)", amount: '600-700 gr' },
            { name: "Qo'ziqorin (shampinyon)", amount: '300 gr' },
            { name: 'Kartoshka', amount: '4-5 dona' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: "Sariyog'", amount: '200 gr' },
            { name: 'Tuxum', amount: '4 dona' },
            { name: 'Tuz, murch, zira', amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Bifshtekslarni tayyorlash: Qiymaga mayda to'g'ralgan piyoz, tuz va murch qo'shib yaxshilab mushtlang. Katta va yassi shakldagi kotletlar yasab, tavada har ikki tomonini qizartirib qovuring.",
            "Qo'ziqorin va kartoshkani qovurish: Kartoshkani to'g'rab, alohida tavada qizarguncha qovuring. Boshqa tavada sariyog'da piyoz va qo'ziqorinlarni qovuring.",
            "Tuxum (Glazunya): Har bir bifshteks uchun bittadan tuxumni sarig'i butun qoladigan qilib alohida qovuring.",
            "Dasturxonga tortish: Tarelkaning bir chetiga qo'ziqorinli kartoshkani soling. Markazga bifshteksni qo'ying va ustiga qovurilgan tuxumni joylashtiring.",
        ],
    },
    'Manti': {
        ingredients: [
            { section: 'Xamir uchun:' },
            { name: 'Un', amount: '1 kg' },
            { name: 'Suv', amount: '2 stakan (iliq)' },
            { name: 'Tuxum', amount: '1 dona' },
            { name: 'Tuz', amount: '1 osh qoshiq' },
            { section: 'Qiymasi uchun:' },
            { name: "Go'sht", amount: '1 kg' },
            { name: "Dumba yog'i", amount: '200-300 gr' },
            { name: 'Piyoz', amount: '1 kg' },
            { name: "Tuz, murch, zira (ko'proq)", amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Xamir: Un, tuxum, suv va tuzdan o'rtacha qattiqlikda xamir qoring. Uni kamida 30-40 daqiqa tindirib qo'ying.",
            "Qiyma: Go'sht, dumba va piyozni mayda to'g'rang. Ziravorlarni qo'shib, piyoz suvi chiqishi uchun yaxshilab aralashtiring.",
            "Yoyish va Tugish: Xamirni juda yupqa qilib yoying va 10x10 sm kattalikdagi kvadratlarga bo'ling. Har bir kvadrat o'rtasiga qiyma qo'yib tuging.",
            "Pishirish: Manti qasqon listlarini yog'lang. Mantilarni terib, qaynayotgan suv ustida 35-45 daqiqa pishiring.",
        ],
    },
    'Honim': {
        ingredients: [
            { section: 'Xamir uchun:' },
            { name: 'Un', amount: '600-700 gr' },
            { name: 'Iliq suv', amount: '1 stakan' },
            { name: 'Tuxum', amount: '1 dona' },
            { name: 'Tuz', amount: '1 choy qoshiq' },
            { section: 'Qiymasi uchun:' },
            { name: "Go'sht", amount: '500 gr' },
            { name: 'Piyoz', amount: '4-5 dona' },
            { name: 'Kartoshka', amount: '1-2 dona' },
            { name: "Dumba yog'i yoki sariyog'", amount: '100 gr' },
            { name: "Tuz, murch, zira", amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Xamir: Un, suv va tuzdan elastik xamir qoring. Uni 20-30 daqiqa tindirib qo'ying.",
            "Qiyma: Piyoz va go'shtni juda mayda somoncha yoki kubik shaklida to'g'rang. Ziravorlar va eritilgan yog'ni qo'shib aralashtiring.",
            "Yoyish: Xamirni iloji boricha yupqa (1 mm) qilib yoying.",
            "Tugish: Yoyilgan xamir yuzasiga qiyma va yog'ni bir tekis qilib yoying. So'ngra xamirni rulet shaklida o'rang.",
            "Pishirish: Manti qasqon listlarini yaxshilab yog'lang va xonimni joylashtiring. Qaynayotgan suv ustida 40-45 daqiqa pishiring.",
            "Xonimning ustiga pomidorli qayla yoki murchli piyoz juda mos tushadi.",
        ],
    },
    'Shovla': {
        ingredients: [
            { name: 'Guruch', amount: '500 gr' },
            { name: "Go'sht", amount: '500 gr' },
            { name: 'Sabzi', amount: '400 gr' },
            { name: 'Piyoz', amount: '3-4 dona' },
            { name: 'Pomidor', amount: '2 dona' },
            { name: "Yog'", amount: '150-200 ml' },
            { name: "Tuz, murch, zira.", amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Qovurish: Qozonda yog'ni qizdirib, piyozni qizarguncha qovuring. Keyin go'shtni solib, yaxshi qizarguncha davom eting.",
            "Pomidor: Ustiga to'g'ralgan pomidorni solib, 2-3 daqiqa qovuring.",
            "Sabzi: Sabzini qo'shing va u yumshaguncha qovuring.",
            "Suv quyish: Masalliqlarni ko'mguncha suv quyib, 20-25 daqiqa qaynatib oling.",
            "Guruch solish: Guruchni yuvib qozonga soling.",
            "Pishirish: Suv miqdori plovdagidan ko'proq bo'lishi kerak. Guruch suvni to'liq yutib, yumshoq bo'lib pishishi kerak.",
            "Damlash: Suvi tortilgach, olovni pastlatib, 15-20 daqiqa dam bering.",
        ],
    },
    'Chuchvara': {
        ingredients: [
            { section: 'Xamir uchun:' },
            { name: 'Un', amount: '500 gr' },
            { name: 'Suv', amount: '1 stakan (iliq)' },
            { name: 'Tuxum', amount: '1 dona' },
            { name: 'Tuz', amount: '1 choy qoshiq' },
            { section: 'Qiyma uchun:' },
            { name: "Go'sht", amount: '300-400 gr' },
            { name: 'Piyoz', amount: '2-3 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: 'Pomidor yoki tomat pastasi', amount: '1 osh qoshiq' },
            { name: 'Kartoshka', amount: '1-2 dona' },
            { name: "Yog'", amount: '100 ml' },
        ],
        steps: [
            "Xamir va tugish: Un, tuxum, suv va tuzdan o'rtacha qattiqroq xamir qoring. 20 daqiqa tindirib, juda yupqa yoying. Kichik kvadratlarga bo'lib, ichiga qiyma solib, mitti chuchvaralar tuging.",
            "Qaylani tayyorlash: Qozonda yog'ni qizdirib, go'shtni va piyozni qovuring. Pomidor, sabzi va kartoshkani solib, suv quyib qaynatishga qo'ying.",
            "Pishirish: Sho'rva 30-40 daqiqa qaynagach, tuzini rostlang va olovni balandlatib, tugilgan chuchvaralarni soling.",
            "Tayyor bo'lishi: Chuchvaralar suv yuziga qalqib chiqqandan so'ng, yana 5-7 daqiqa qaynatiladi.",
        ],
    },
    'Manpar': {
        ingredients: [
            { section: 'Xamirni tayyorlash' },
            { name: 'Un', amount: '500 gr' },
            { name: 'Tuxum', amount: '1 dona' },
            { name: 'Iliq suv', amount: '0,5 stakan' },
            { name: 'Tuz', amount: '1 choy qoshiq' },
            { section: 'Qayla tayyorlash' },
            { name: "Go'sht", amount: '400 gr' },
            { name: 'Piyoz', amount: '2 ta' },
            { name: 'Pomidor', amount: '2 ta' },
            { name: "Bulg'or qalampiri", amount: '2 ta' },
            { name: 'Sarimsoq piyoz', amount: "Ta'bga ko'ra" },
            { name: 'Sabzi', amount: '1 ta' },
        ],
        steps: [
            "Xamir tayyorlash: Qattiqroq xamir qorib, 30 daqiqa tindiring. Keyin yupqa yoyib, kichik kvadratchalar shaklida kesing yoki qaynoq suvda pishirib oling.",
            "Qozonda yog'ni qizdirib, go'shtni qizarguncha qovuring. Piyoz, sabzi va pomidorni solib qovurishda davom eting.",
            "Bulg'or qalampiri va sarimsoqni qo'shib, 2-3 daqiqa qovuring.",
            "Masalliqlarni ko'mguncha suv quyib, past olovda 30-40 daqiqa qaynatib oling.",
            "Ziravorlarni qo'shib, ta'mini tekshiring.",
            "Kosa tubiga avval pishgan xamirni soling, ustidan qaynoq qaylani quying.",
        ],
    },
    'Befstroganov': {
        ingredients: [
            { name: "Go'sht", amount: '600 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Qaymoq (slivki) yoki smetana', amount: '200 ml' },
            { name: "Sariyog'", amount: '50 gr' },
            { name: 'Un', amount: '1 osh qoshiq' },
            { name: 'Kartoshka', amount: '1 kg' },
            { name: 'Sut', amount: '150-200 ml' },
            { name: 'Tuz, murch', amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Go'shtni to'g'rash: Go'shtni tolalariga qarshi qilib, ingichka va uzunchoq shaklida to'g'rang.",
            "Qovurish: Tavada sariyog'ni eritib, go'shtni baland olovda har tomoni qizarguncha 5-7 daqiqa qovuring. Piyozni qo'shib, yumshaguncha davom eting.",
            "Sous: Ustiga un sepib aralashtiring, so'ng qaymoq quying. Tuz va murch qo'shing.",
            "Dimlash: Olovni pasaytirib, sous quyulguncha va go'sht yumshaguncha 10-15 daqiqa dimlang.",
            "Kartoshkani tozalab, tuzli suvda pishguncha qaynating.",
            "Suvini to'kib, kartoshkani issiqligida yaxshilab ezing.",
            "Ichiga sariyog' va issiq sutni oz-ozdan quyib, bir xil massa bo'lguncha aralashtiring.",
        ],
    },
    'Koza-kifta Dimlama': {
        ingredients: [
            { name: "Go'sht", amount: '600-800 gr' },
            { name: 'Kartoshka', amount: '4-5 dona' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: "Bulg'or qalampiri", amount: '1-2 dona' },
            { name: 'Pomidor', amount: '2 dona (yoki tomat pastasi)' },
            { name: "Sariyog'", amount: "Har bir ko'zachaga 1 choy qoshiqdan" },
            { name: "Tuz, murch, zira, kashnich urug'i", amount: '' },
        ],
        steps: [
            "Tayyorgarlik: Go'sht va barcha sabzavotlarni kichik kubik shaklida to'g'rab oling.",
            "Qatlamlash: Ko'zachalarga masalliqlarni quyidagi tartibda soling: Pastki qismga go'sht, ustidan piyoz va sabzi, keyin bulg'or qalampiri va pomidor, eng ustiga kartoshkani joylang.",
            "Yog' va suv: Har bir ko'zacha ustiga bir bo'lak sariyog' qo'ying va yarim piyola suv quying.",
            "Yopish: Ko'zacha og'zini o'z qopqog'i yoki xamir bilan mahkam yoping.",
            "Pishirish: Sovuq duxovkaga qo'ying va haroratni 180-200 darajaga ko'taring. Taom taxminan 1.5-2 soat davomida dimlanadi.",
            "Ko'za kifta issiq holda, ko'zachaning o'zida tortiladi.",
        ],
    },
    'Zharkof': {
        ingredients: [
            { name: "Go'sht", amount: '700-800 gr' },
            { name: 'Kartoshka', amount: '1 kg' },
            { name: 'Piyoz', amount: '2-3 dona' },
            { name: 'Sabzi', amount: '1-2 dona' },
            { name: 'Tomat pastasi', amount: '1 osh qoshiq' },
            { name: "Bulg'or qalampiri", amount: '1 dona' },
            { name: "Yog'", amount: '150 ml' },
            { name: "Tuz, murch, zira, kashnich urug'i", amount: '' },
            { name: 'Suv:', amount: '1.5-2 stakan' },
        ],
        steps: [
            "Qovurish: Qozonda yog'ni qizdirib, go'sht bo'laklarini tillarang bo'lguncha baland olovda qovuring.",
            "Sabzavotlarni qo'shish: Ustiga piyozni solib qizartiring, so'ngra sabzi va pomidorni qo'shib qovuring.",
            "Kartoshkani solish: Kubik shaklida to'g'ralgan kartoshkalarni soling. 5-10 daqiqa birga qovuring.",
            "Ziravorlash va suv: Tuz va barcha ziravorlarni seping. Masalliqlarni ko'rmadigan darajada qaynoq suv quying.",
            "Dimlash: Qozon qopqog'ini yopib, olovni pasaytiring. 40-50 daqiqa davomida go'sht va kartoshka yumshaguncha pishiring.",
        ],
    },
    'Jizz': {
        ingredients: [
            { name: "Go'sht", amount: '1 kg' },
            { name: "Dumba yog'i", amount: '150-200 gr' },
            { name: 'Piyoz', amount: '2-3 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: "Ziravorlar: Tuz, ko'p miqdorda zira, murch, kashnich urug'i", amount: '' },
            { name: 'Suv (dimlash uchun)', amount: '100-150 ml' },
        ],
        steps: [
            "Go'shtni tayyorlash: Go'shtni o'rtacha bo'laklarga bo'ling. Unga tuz va hamma ziravorlarni surtib, 30 daqiqa marinadalab qo'ying.",
            "Yog'ni eritish: Qozonga avval dumba yog'ini solib, qizartirib eritib oling.",
            "Qovurish: Baland olovda go'shtni qizigan yog'ga soling. Har tomoni to'q jigarrang bo'lguncha yaxshilab qovuring.",
            "Dimlash: Olovni eng past darajaga tushiring. Go'sht ustidan bir oz suv quying. Qozon qopqog'ini jips yopib, 45-60 daqiqa davomida dimlang.",
            "Piyoz bilan aralashtirish: Taom tayyor bo'lishiga 5 daqiqa qolganda, to'g'ralgan piyozni qo'shib, qopqoqni yana yopib qo'ying.",
            "Lagan o'rtasiga go'shtni suzing, atrofini piyoz, limon bo'laklari va pomidorlar bilan bezang.",
        ],
    },
    "Uyg'ur Lagmon": {
        ingredients: [
            { section: 'Xamir uchun:' },
            { name: 'Un', amount: '500-600 gr' },
            { name: 'Iliq suv', amount: '200-250 ml' },
            { name: 'Tuz', amount: '1 choy qoshiq' },
            { name: 'Soda', amount: 'Yarim choy qoshiq' },
            { section: 'Qaylasi uchun:' },
            { name: "Go'sht", amount: '500 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Pomidor', amount: '3-4 dona' },
            { name: "Bulg'or qalampir", amount: '2-3 dona' },
            { name: 'Barg pekin karami', amount: '5-6 dona' },
            { name: 'Daykon turpi', amount: '1 dona' },
            { name: 'Sarimsoq piyoz', amount: '1 bosh' },
            { name: "Zira, kashnich urug'i, tuz va murch", amount: '' },
        ],
        steps: [
            "Un, tuz va suvdan qattiqroq xamir qoring. Yaxshilab mushtlab, ustini yopib 30 daqiqa tindiring. Ingichka pitalar qiling.",
            "Pitalarni tindirib, qo'l bilan cho'zib, qaynab turgan tuzli suvda 2-3 daqiqa pishirib oling. Sovuq suvda chayib, yog'lab qo'ying.",
            "Qovurish: Qozonda yog'ni qizdirib, go'shtni baland olovda qizarguncha qovuring.",
            "Piyoz va Pomidor: Piyozni solib biroz qovurgach, pomidor va pomidor pastasini qo'shing.",
            "Sabzavotlar: Navbati bilan turp, pekin karami va bulg'or qalampirini soling. Sabzavotlar biroz qirsillab turishi lozim.",
            "Likopchaga avval xamirni soling, ustidan issiq qaylani quyib, ko'katlar bilan bezating.",
        ],
    },
    'Tova-Manti': {
        ingredients: [
            { section: 'Xamir uchun' },
            { name: 'Un', amount: '500-600 gr' },
            { name: 'Tuxum', amount: '1 dona' },
            { name: 'Iliq suv', amount: '1 stakan' },
            { name: 'Tuz', amount: '1 choy qoshiq' },
            { section: 'Qiyma uchun' },
            { name: "Go'sht", amount: '400 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: "Tuz, murch, zira", amount: "ta'bga ko'ra" },
            { section: 'Qayla uchun' },
            { name: 'Piyoz', amount: '1-2 dona' },
            { name: 'Sabzi', amount: '1-2 dona' },
            { name: "Bulg'or qalampiri", amount: '2 dona' },
            { name: 'Pomidor', amount: '2 dona' },
            { name: 'Sarimsoq piyoz', amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Un, tuxum, tuz va suvdan o'rtacha qattiqlikda xamir qoring. 30 daqiqa tindirib, yupqa yoying va kvadratlarga bo'lib, go'shtli manti tuging.",
            "Chuqur tavada avval piyoz, sarimsoq va sabzini qovuring. Pomidor, bulg'or qalampirini qo'shib, yumshaguncha qovuring.",
            "Tayyor sabzavotli qayla ustiga mantilarni bir-biriga tegmaydigan qilib tering.",
            "Tomat pastasi aralashtirilgan bir stakan iliq suvni manti bo'ylari bo'ylab ehtiyotkorlik bilan quying.",
            "Tava qopqog'ini mahkam yopib, olovni pasaytiring va 40-50 daqiqa davomida dimlab pishiring.",
        ],
    },
    'Kotleta po Kiyevski': {
        ingredients: [
            { name: 'Tovuq filesi', amount: '2 dona (kattaroq)' },
            { name: "Sariyog'", amount: '100 gr' },
            { name: 'Ukrop', amount: "Bir bog' (mayda to'g'ralgan)" },
            { name: 'Tuxum', amount: '2-3 dona' },
            { name: 'Un', amount: 'Yarim stakan' },
            { name: 'Paneer (suxari)', amount: '1 stakan' },
            { name: 'Tuz, murch', amount: "ta'bga ko'ra" },
            { name: "O'simlik yog'i: qovurish uchun", amount: '' },
        ],
        steps: [
            "Yashil sariyog': Yumshoq sariyog'ni mayda to'g'ralgan ukrop va tuz bilan aralashtiring. Barmoqcha shakllar yasab, muzlatgichga 15-20 daqiqaga qo'ying.",
            "Fileni tayyorlash: Tovuq filesini kapalak shaklida oching va ehtiyotkorlik bilan urib yupqalang. Tuz va murch seping.",
            "Tugish: Muzlagan sariyog'ni filening o'rtasiga qo'ying va go'shtni mahkam qilib rulet shaklida o'rang.",
            "Dvoynoy panirovka: Kotletani avval unga, keyin tuxumga, so'ngra suxariga, va yana bir marta tuxumga va suxariga bulang.",
            "Qovurish: Kotletalarni ko'p miqdordagi qizigan yog'da har tomonini 3-5 daqiqa qizarguncha qovuring.",
            "Pishirish: Duxovkaga 180 darajada 10-12 daqiqaga qo'ying, ichidagi go'sht to'liq pishsin.",
            "Kotletani kesganingizda ichidan xushbo'y sariyog' oqib chiqishi kerak.",
        ],
    },
    'Chahonbili': {
        ingredients: [
            { name: 'Tovuq', amount: '1 kg' },
            { name: 'Piyoz', amount: '4-5 dona' },
            { name: 'Pomidor', amount: '500 gr' },
            { name: "Bulg'or qalampir", amount: '1-2 dona' },
            { name: 'Sarimsoq piyoz', amount: '3-4 dona' },
            { name: "Sariyog'", amount: '30-50 gr' },
            { name: 'Ziravorlar: Xmeli-suneli, kashnich, murch va tuz', amount: "Ta'bga ko'ra" },
            { name: 'Rayhon, petrushka', amount: '' },
        ],
        steps: [
            "Tovuq bo'laklarini hech qanday yog'siz baland olovda har tomonini qizarguncha 10-12 daqiqa qovuring.",
            "Alohida tovada piyozni sariyog'da tilla rangga kirguncha sote qilib oling va tovuq ustiga soling.",
            "Pomidorlarni mayda to'g'rab qozonga qo'shing. Bulg'or qalampirini ham soling.",
            "Olovni pasaytirib, qozon qopqog'ini yoping va 20-25 daqiqa davomida dimlang.",
            "Tayyor bo'lishidan 5 daqiqa oldin sarimsoqpiyoz, tuz, murch, xmeli-suneli va ko'katlarni qo'shing.",
        ],
    },
    // ===== IFTORLIK =====
    'Mastava': {
        ingredients: [
            { name: "Go'sht", amount: '400-500 gr' },
            { name: 'Guruch', amount: '150-200 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Sabzi', amount: '2 dona' },
            { name: 'Kartoshka', amount: '2 dona' },
            { name: 'Pomidor', amount: '2 dona' },
            { name: "Yog'", amount: '100-150 ml' },
            { name: "Tuz, murch, zira, kashnich urug'i", amount: '' },
        ],
        steps: [
            "Qovurish: Qozonda yog'ni qizdirib, go'sht bo'laklarini qizarguncha qovuring. Piyozni solib, tillarang bo'lguncha davom eting.",
            "Sabzavotlar: Pomidor va sabzini qo'shib 5-7 daqiqa qovuring. Kartoshkani solib, yana aylantiring.",
            "Suv quyish: Qozonga 2-2.5 litr sovuq suv quying va qaynab chiqqach, 20-25 daqiqa mittilatib qaynating.",
            "Guruch solish: Yuvilgan guruchni soling, tuz va ziravorlarni qo'shing. Guruch pishguncha 15-20 daqiqa qaynatishda davom eting.",
            "Damlash: Olovni o'chirib, qozon qopqog'ini yopgan holda 10 daqiqa tindiring.",
            "Mastavani kosalarga suzib, ustidan qatiq yoki suzma hamda ko'katlar sepib torting.",
        ],
    },
    'Chechevitsa turkcha': {
        ingredients: [
            { name: 'Qizil chechevitsa', amount: '1 stakan' },
            { name: 'Piyoz', amount: '1 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: 'Kartoshka', amount: '1 dona' },
            { name: "Sariyog'", amount: '1 osh qoshiq' },
            { name: 'Pomidor pastasi', amount: '1 choy qoshiq' },
            { name: 'Suv', amount: '1,5 litr' },
            { name: 'Quritilgan yalpiz, tuz, murch', amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Qozonda sariyog'ni eritib, piyozni shaffof bo'lguncha qovuring. Sabzi va kartoshkani qo'shib, 2-3 daqiqa qovurishda davom eting.",
            "Yasmiqni va pomidor pastasini sabzavotlar ustiga solib aralashtiring.",
            "Ustidan suv quyib, qaynab chiqqach, olovni pasaytiring. 20-25 daqiqa pishiring.",
            "Taom pishgach, blender yordamida pyure holatiga keltiring.",
            "Tuz, murch va quritilgan yalpizni qo'shing.",
        ],
    },
    "Qaynatma sho'rva": {
        ingredients: [
            { name: "Go'sht", amount: '500-700 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Sabzi', amount: '2 dona' },
            { name: 'Kartoshka', amount: '3-4 dona' },
            { name: 'Pomidor', amount: '1-2 dona' },
            { name: "Bulg'or qalampiri", amount: '1 dona' },
            { name: "Yog'", amount: '100-150 ml' },
            { name: "Tuz, murch, zira, kashnich urug'i", amount: '' },
        ],
        steps: [
            "Go'shtni qaynatish: Qozonga sovuq suv quyib, go'shtni soling. Ko'pikni yaxshilab olib tashlang.",
            "Piyoz va ziravorlar: To'g'ralgan piyoz, tuz va ziravorlarni soling. Kamida 1 soat miltilatib qaynating.",
            "Sabzavotlar: Sabzi va bulg'or qalampirini yirik bo'laklarga bo'lib soling. Pomidorni ham qo'shing.",
            "Kartoshka: Go'sht pishishiga 30-40 daqiqa qolganda kartoshkalarni soling.",
            "Yakuniy bosqich: Barcha masalliqlar yumshagach, 10 daqiqa dam bering.",
            "Go'sht va sabzavotlarni alohida idishga, sho'rvasini kosalarga suzing. Ko'katlar seping.",
        ],
    },
    'Borsh': {
        ingredients: [
            { name: "Go'sht", amount: '500 gr' },
            { name: 'Lavlagi', amount: '2 dona' },
            { name: 'Piyoz', amount: '1 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: 'Kartoshka', amount: '3 dona' },
            { name: 'Karam', amount: '300 gr' },
            { name: 'Pomidor pastasi', amount: '2 osh qoshiq' },
            { name: 'Limon suvi yoki uksus', amount: '1 osh qoshiq' },
            { name: "Tuz, murch, lavr yaprog'i, sarimsoqpiyoz (2 dona)", amount: '' },
        ],
        steps: [
            "Bulyon: Go'shtni sovuq suvga solib, 1,5-2 soat mittilatib qaynating. Ko'pigini olishni unutmang.",
            "Sabzavotlar: Pishgan bulyonga kartoshkani soling. 10 daqiqadan so'ng karamni qo'shing.",
            "Zajarka: Tovada piyoz va sabzini qovuring. Qirg'ichdan o'tgan lavlagini soling. Limon suvi va pomidor pastasini qo'shib, 5-7 daqiqa past olovda dimlang.",
            "Birlashtirish: Tayyor lavlagli qovurmani qozonga soling. Tuz, murch va lavr yaprog'ini qo'shing.",
            "Yakun: Yana 10 daqiqa qaynatib, maydalangan sarimsoqpiyozni soling. 15-20 daqiqa dam olishi kerak. Smetana va ko'k piyoz bilan torting.",
        ],
    },
    'Kuk-si': {
        ingredients: [
            { section: 'Kuksi-muri (Suyuqligi)' },
            { name: 'Suv (Muzdek)', amount: '2 litr' },
            { name: 'Soya sousi', amount: '100-120 ml' },
            { name: 'Shakar', amount: '2 osh qoshiq' },
            { name: 'Tuz', amount: '1 osh qoshiq' },
            { name: 'Uksus', amount: '2-3 osh qoshiq' },
            { name: 'Bodring', amount: '1 dona' },
            { name: 'Pomidor', amount: '1 dona' },
            { section: 'Garnirlar (Kuksi-chay)' },
            { name: 'Lapsha', amount: '500 gr' },
            { name: "Go'sht", amount: '300 gr' },
            { name: 'Karam', amount: '400 gr' },
            { name: 'Tuxum', amount: '3 dona' },
            { name: "O'simlik yog'i", amount: '100 ml' },
            { name: 'Sarimsoqpiyoz', amount: '3-4 dona' },
        ],
        steps: [
            "Muri: Muzdek suvga tuz, shakar, soya sousi va uksusni solib aralashtiring. Bodring va pomidorni qirg'ichdan o'tkazib soling, muzlatgichga qo'ying.",
            "Go'sht: Go'shtni piyoz bilan baland olovda 10-15 daqiqa qovurib pishiring.",
            "Karamli salat: Karamni yupqa to'g'rab, tuz bilan ezing. Ustiga murch va qizdirilgan yog'ni quyib aralashtiring.",
            "Tuxumli quymoq: Tuxumlarni ko'pirtirib, tovada yupqa quymoqlar pishiring va somoncha to'g'rang.",
            "Lapsha: Lapshani qaynatib, sovuq suvda 2-3 marta chayib oling.",
            "Kosaning tubiga lapsha soling, ustiga har bir garnirdan qo'ying va muzdek murini quying.",
        ],
    },
    "Lag'mon": {
        ingredients: [
            { name: "Go'sht", amount: '400-500 gr' },
            { name: 'Xamir', amount: '500 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: 'Kartoshka', amount: '2 dona' },
            { name: "Bulg'or qalampiri", amount: '2 dona' },
            { name: 'Pomidor', amount: '2 dona' },
            { name: 'Sarimsoqpiyoz', amount: '3-4 dona' },
            { name: "Jandun (loviya) yoki turp", amount: "Ta'bga ko'ra" },
            { name: "Ziravorlar: Tuz, murch, zira, kashnich urug'i va badyan", amount: '' },
        ],
        steps: [
            "Qovurish: Qozonda yog'ni qizdirib, go'shtni qizarguncha qovuring. Piyozni solib, tillarang bo'lguncha davom eting.",
            "Sabzavotlar: Tomat, pomidor, sabzi va kartoshkani solib 5-7 daqiqa qovuring. Bulg'or qalampiri va sarimsoqni qo'shing.",
            "Suv quyish: Masalliqlarni ko'mguncha va biroz ortiqcha qaynoq suv quying. Taxminan 1.5-2 litr.",
            "Mittilatib qaynatish: Badyan yulduzchasini va ziravorlarni solib, past olovda 30-40 daqiqa qaynating.",
            "Xamir: Lagmon xamirini tuzli suvda pishirib, suzib oling.",
            "Kosa tubiga pishgan xamirni soling, ustidan qaylasidan quying. Kashnich va ko'k piyoz sepib torting.",
        ],
    },
    'Bulyonli Dolma': {
        ingredients: [
            { name: "Go'sht", amount: '500 gr' },
            { name: 'Karam', amount: '400-500 gr' },
            { name: 'Kartoshka', amount: '3-4 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Pomidor', amount: '1 dona' },
            { name: "Sariyog'", amount: '20 gr' },
            { name: "Ziravorlar: Tuz, murch, lavr yaprog'i", amount: '' },
            { name: "Dasturxonga: Smetana va ko'katlar", amount: '' },
        ],
        steps: [
            "Qiymani tayyorlash: Qiyma, guruch, piyoz va ziravorlarni aralashtiring.",
            "To'ldirish: Bulg'or qalampir va pomidorlarni ichini tozalab, qiyma bilan to'ldiring.",
            "Zajarka: Qozonda yog'ni qizdirib, suyakli go'shtni qizartirib qovuring. Piyoz va sabzini solib, tomat pastasini qo'shing.",
            "Taxlash: Qovurilgan masalliqlar ustiga to'ldirilgan sabzavotlarni va kartoshka bo'laklarini tizing.",
            "Pishirish: Ustidan qaynoq suv quying. Qaynab chiqqach, olovni pasaytirib, 45-50 daqiqa mittilatib qaynating.",
        ],
    },
    'Somsa': {
        ingredients: [
            { section: 'Xamiri uchun:' },
            { name: 'Un', amount: '800 g - 1 kg' },
            { name: 'Suv (iliq)', amount: '500 ml' },
            { name: 'Tuz', amount: '1 osh qoshiq' },
            { name: "Sariyog' yoki margarin", amount: '200-250 g' },
            { section: 'Qiymasi uchun:' },
            { name: "Go'sht", amount: '600-700 g' },
            { name: "Dumba yog'i", amount: '100-150 g' },
            { name: 'Piyoz', amount: '700-800 g' },
            { name: "Tuz, murch, zira.", amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Xamir: Iliq suvda tuzni eritib, undan qattiqroq xamir qoring. 20 daqiqa tindiring.",
            "Yoyish: Xamirni 2-3 bo'lakka bo'lib, juda yupqa qilib yoying.",
            "Yog'lash: Yoyilgan xamir yuzasiga eritilgan sariyog'ni surting.",
            "O'rash: Yog'langan xamirni rulet shaklida o'rang. Ruletni spiral shaklida taxlab, muzlatgichga 1 soatga qo'ying.",
            "Qiyma: Go'sht, dumba va piyozni mayda to'g'rang, ziravorlar qo'shib aralashtiring.",
            "Tugish: Ruletni bo'laklarga kesib, har birini yoyib qiyma solib, uchburchak shaklda tuging.",
            "Pishirish: Somsalar ustiga tuxum sarig'i surtib, kunjut seping. 200 darajada 30-35 daqiqa pishiring.",
        ],
    },
    'OLOT Somsa': {
        ingredients: [
            { section: 'Xamir uchun' },
            { name: 'Un', amount: '1 kg' },
            { name: 'Suv', amount: '500 ml' },
            { name: 'Tuz', amount: '1 osh qoshiq' },
            { section: "Qiymasi (Olotcha o'ziga xoslik)" },
            { name: "Go'sht", amount: '700 gr' },
            { name: "Dumba yog'i", amount: '150-200 ml' },
            { name: 'Piyoz', amount: '800 gr' },
            { name: 'Pomidor', amount: '2-3 dona' },
            { name: "Bulg'or qalampiri", amount: '1 dona' },
            { name: "Ziravorlar: Tuz, mo'l-ko'l murch va zira.", amount: '' },
        ],
        steps: [
            "Tuzli suvdan qattiq xamir qoring. Yaxshilab mushtlab, 30 daqiqa tindiring.",
            "Yoyish: Xamirni kichik zuvalachalarga bo'ling va chetlarini yupqaroq qilib yoying.",
            "Tugish: O'rtasiga mo'lroq qiyma soling. To'rtburchak shaklda tuging.",
            "Duxovka: 220-230 darajada 25-30 daqiqa pishiring.",
            "Siri: Somsa pishib chiqqach, ustiga sovuq suv sepib, 5 daqiqaga yopib qo'ying. Bu qobig'ini qarsildoq va yumshoq qiladi.",
        ],
    },
    'Gumma': {
        ingredients: [
            { section: 'Xamir uchun' },
            { name: 'Un', amount: '1 kg' },
            { name: 'Iliq suv', amount: '300 ml' },
            { name: 'Tuz', amount: '1 choy qoshiq' },
            { name: 'Shakar', amount: '0.5 choy qoshiq' },
            { name: "O'simlik yog'i", amount: '2 osh qoshiq' },
            { section: 'Qiymasi (Klassik jigarli)' },
            { name: "Jigar (mol yoki qo'y)", amount: '300 gr' },
            { name: "O'pka yoki go'sht", amount: '200 gr' },
            { name: 'Piyoz', amount: '3-4 dona' },
            { name: "Dumba yog'i", amount: '50-70 g' },
            { name: "Tuz, mo'l-ko'l murch, zira", amount: '' },
        ],
        steps: [
            "Hamir: Iliq suvga masalliqlarni solib, o'rtacha yumshoqlikdagi xamir qoring. 1 soatga issiq joyga oshirishga qo'ying.",
            "Qiyma: Jigar va o'pkani go'shtqiymalagichdan o'tkazing. Piyozni mayda to'g'rab, ziravorlar bilan aralashtiring.",
            "Bo'laklash: Oshgan xamirni kichik zuvalachalarga bo'ling.",
            "Yoyish: Har birini yupqa qilib yoyib, o'rtasiga 1 osh qoshiq qiyma soling.",
            "Tugish: Yarim oy shaklida tuging va chetlarini yaxshilab yopishtiring.",
            "Pishirish: Tovada qizigan yog'da har ikki tomonini tillarang bo'lguncha qovuring.",
            "Gumma murchli tomat sousi bilan issig'ida yeyiladi.",
        ],
    },
    'Moshkichir': {
        ingredients: [
            { name: 'Mosh', amount: '1 stakan' },
            { name: 'Guruch', amount: '1 stakan' },
            { name: "Go'sht", amount: '300-400 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Sabzi', amount: '2 dona' },
            { name: "Yog'", amount: '150 ml' },
            { name: 'Suv', amount: '1,5-2 litr' },
            { name: "Zira, tuz, murch", amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Qozonda yog'ni qizdirib, go'shtni qizartirib qovuring. Piyozni solib, tillarang bo'lguncha davom eting. Sabzini qo'shib, biroz yumshaguncha qovuring.",
            "Qozonga suv quyib, yuvilgan moshni soling. Tuzni mosh yorilmaguncha solmang.",
            "Mosh past olovda qaynab, po'sti yorilib chiqqandan keyin, guruchni qo'shing.",
            "Guruch suvni shimib, yumshaguncha tez-tez aralashtiring. Tuz va ziravorlarni qo'shing.",
            "Suvi to'liq tortilgach, olovni o'chirib, 10-15 daqiqa dam bering.",
            "Moshkichiri ustiga qovurilgan piyoz-dog' yoki qatiq qo'shib tortilsa, mazasi mukammal bo'ladi.",
        ],
    },
    'Ukraincha Shi': {
        ingredients: [
            { name: "Go'sht", amount: '500 gr' },
            { name: 'Karam', amount: '400-500 gr' },
            { name: 'Kartoshka', amount: '3-4 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Pomidor', amount: '1 dona' },
            { name: "Sariyog'", amount: '20 gr' },
            { name: "Ziravorlar: Tuz, murch, lavr yaprog'i.", amount: '' },
            { name: "Dasturxonga: Smetana va ko'katlar.", amount: '' },
        ],
        steps: [
            "Bulyon: Go'shtni sovuq suvga solib, 1.5-2 soat miltilatib qaynatib pishiring. Ko'pigini oling.",
            "Karam va kartoshka: Tayyor bulyonga kartoshkani soling. Qaynab chiqqach, karamni qo'shing va 10-15 daqiqa qaynating.",
            "Zajarka: Tovada sariyog'ni eritib, piyoz va sabzini qovuring. Pomidorni qo'shib, biroz dimlang va qozonga soling.",
            "Ziravorlar: Tuz, murch va lavr yaprog'ini solib, yana 5-10 daqiqa past olovda pishiring.",
            "Dam berish: Shi pishgach, olovni o'chirib, 15 daqiqa dam bering.",
        ],
    },
    'Tuxum barak': {
        ingredients: [
            { section: 'Xamiri uchun' },
            { name: 'Un', amount: '500 gr' },
            { name: 'Suv', amount: '200-250 ml' },
            { name: 'Tuz', amount: '1 choy qoshiq' },
            { name: 'Tuxum', amount: '1 dona' },
            { section: 'Qiymasi uchun' },
            { name: 'Tuxum', amount: '8-10 dona' },
            { name: "O'simlik yog'i", amount: '100-150 ml' },
            { name: 'Sut', amount: '50-100 ml' },
            { name: "Ziravorlar: Tuz, murch va ko'k piyoz.", amount: '' },
        ],
        steps: [
            "Hamir: Qattiqroq xamir qoring, yaxshilab mushtlang va 20 daqiqa tindiring. Juda yupqa qilib yoying.",
            "Kiyma: Tuxumlarni chaqib, sut, yog' va ziravorlarni solib aralashtiring.",
            "Tugish: Yoyilgan xamirdan 8x8 sm to'rtburchaklar kesib oling. Yon tomonlarini yopishtirib, usti ochiq konvert yasang.",
            "To'ldirish: Har bir konvertga suyuq tuxumli aralashmani quying. Tepasini tezda yopishtirib, qaynab turgan suvga tashlang.",
            "Pishirish: Tuxum baraklar suv yuzasiga qalqib chiqqach, yana 3-4 daqiqa qaynatiladi.",
        ],
    },
    'Qurtoba': {
        ingredients: [
            { name: "Go'sht", amount: '500 gr' },
            { name: 'Qurt', amount: '15-20 dona' },
            { name: 'Piyoz', amount: '2-3 dona' },
            { name: "Yog'", amount: '100 ml' },
            { name: 'Kartoshka', amount: '2-3 dona' },
            { name: "Tuz (ehtiyot bo'ling, qurt sho'r), murch, zira.", amount: '' },
            { name: "Non: 1-2 dona issiq patir", amount: '' },
        ],
        steps: [
            "Qurtni tayyorlash: Qurtlarni iliq suvda yumshatib, ezib, quyuq sut holatiga keltiring.",
            "Go'shtni qovurish: Qozonda yog'ni qizdirib, go'shtni qizartirib qovuring. Piyozni solib, tillarang bo'lguncha davom eting.",
            "Qaynatish: Ustidan suv quyib, go'sht yumshaguncha taxminan 1 soat miltilatib qaynating.",
            "Qurtni qo'shish: Go'sht pishgach, olovni eng past darajaga tushiring. Ezilgan qurtni asta-sekin quyib, to'xtovsiz aralashtiring. Qurtni qo'shgandan keyin qattiq qaynatmang.",
            "Tuzlash: Sho'rvani tatib ko'ring, qurtning sho'ri yetarli bo'lsa, tuz shart emas.",
            "Laganga issiq nonlarni to'g'rang. Ustidan go'sht va qaynoq qurtobni quying. Murch va ko'k piyoz seping.",
        ],
    },
    'Moshhorda': {
        ingredients: [
            { name: 'Mosh', amount: '1 stakan' },
            { name: 'Guruch', amount: 'yarim stakan' },
            { name: "Go'sht", amount: '300-400 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Sabzi', amount: '1-2 dona' },
            { name: 'Pomidor', amount: '1-2 dona' },
            { name: "Yog'", amount: '150 ml' },
            { name: "Tuz, murch, zira va kashnich urug'i", amount: '' },
        ],
        steps: [
            "Qovurish: Qozonda yog'ni qizdirib, piyozni qizartirib, go'shtni qovuring. Pomidor va sabzini qo'shib, 5-7 daqiqa qovuring.",
            "Moshni solish: 2-2,5 litr sovuq suv quyib, yuvilgan moshni soling. Tuzni mosh pishib, po'sti yorilgandan keyin soling.",
            "Qaynash: Mosh gullaguncha past olovda qaynatiladi.",
            "Guruch solish: Mosh pishgach, yuvilgan guruchni soling, tuz va ziravorlarni qo'shing. 15-20 daqiqa miltilatib qaynating.",
            "Tayyor bo'lgach, olovni o'chirib, 10 daqiqa dam bering. Kosalarga suzib, qatiq va ko'katlar sepib torting.",
        ],
    },
    'Turk Menemeni': {
        ingredients: [
            { name: 'Pomidor', amount: '3 dona' },
            { name: 'Yashil qalampir', amount: '2-3 dona' },
            { name: 'Tuxum', amount: '2-3 dona' },
            { name: "Sariyog'", amount: '1 osh qoshiq' },
            { name: 'Piyoz (ixtiyoriy)', amount: "Yarimta mayda to'g'ralgan" },
            { name: 'Tuz, murch, qizil pul-biber.', amount: '' },
        ],
        steps: [
            "Qalampirni qovurish: Tovada sariyog'ni eritib, mayda to'g'ralgan qalampirlarni yumshaguncha 2-3 daqiqa qovuring.",
            "Pomidor: Ustiga to'g'ralgan pomidorlarni soling. Qopqog'ini yopib, pomidorlar ezilib, suvi chiqquncha 5-7 daqiqa dimlang.",
            "Ziravorlar: Tuz va murch qo'shing. Pomidorlar biroz quyuqlashishi kerak.",
            "Tuxum: Tuxumlarni soling. Tuxum oqi pishishi bilan, sarig'i hali biroz namligida olovni o'chiring.",
            "Ustiga pul-biber seping. Menemen issiq oq non bilan birga tortiladi.",
        ],
    },
    'Golubci': {
        ingredients: [
            { name: 'Karam', amount: '1 dona' },
            { name: 'Qiyma', amount: '500-600 gr' },
            { name: 'Guruch', amount: '100 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: 'Pomidor pastasi', amount: '2 osh qoshiq' },
            { name: 'Smetana', amount: '2 osh qoshiq' },
            { name: "Tuz, murch, zira va lavr yaprog'i", amount: '' },
        ],
        steps: [
            "Karamni tayyorlash: O'zagini o'yib, qaynab turgan suvga soling. Barglari yumshab ajralishni boshlaganda ajratib oling.",
            "Qiyma: Qiyma, guruch, piyoz va ziravorlarni aralashtiring.",
            "Tugish: Karam bargiga qiyma solib, zich qilib rulet shaklida o'rang.",
            "Qaylasi: Qozonda piyoz va sabzi qovuring, pomidor pastasi va smetana qo'shib, 1 stakan suv quying.",
            "Pishirish: Golubsini qozonga zich tizing, ustidan qayla quying. Lavr yaprog'ini solib, past olovda 45-50 daqiqa dimlang.",
        ],
    },
    'Gan-Pan': {
        ingredients: [
            { name: 'Guruch', amount: '2-3 stakan' },
            { name: "Go'sht", amount: '400 gr' },
            { name: 'Piyoz', amount: '2 dona' },
            { name: 'Sabzi', amount: '1 dona' },
            { name: "Bulg'or qalampir", amount: '2 dona' },
            { name: 'Pekin karam', amount: '4-5 barg' },
            { name: 'Pomidor', amount: '2 dona' },
            { name: 'Sarimsoqpiyoz', amount: '3-4 dona' },
            { name: 'Soya sousi', amount: '2 osh qoshiq' },
            { name: 'Tuz, murch, zira', amount: '' },
        ],
        steps: [
            "Guruchni yog'siz, faqat tuzli suvda mittilatib, don-don bo'ladigan qilib pishirib oling.",
            "Qozonda yog'ni baland olovda qizdirib, go'shtni qizartirib qovuring.",
            "Navbati bilan piyoz, pomidor va sabzavotlarni solib, baland olovda 5-7 daqiqa qovuring. Ziravorlar va sarimsoqni qo'shing.",
            "Likopchaning bir chetiga guruchni, ikkinchi chetiga qaylasini solib, ko'k piyoz sepib torting.",
        ],
    },
    'Qovurma-Lagmon': {
        ingredients: [
            { name: 'Xamir', amount: '500 gr' },
            { name: "Go'sht", amount: '300-400 gr' },
            { name: 'Piyoz', amount: '1-2 dona' },
            { name: "Bulg'or qalampiri", amount: '2 dona' },
            { name: 'Pomidor', amount: '1-2 dona' },
            { name: 'Sarimsoqpiyoz', amount: '3-4 dona' },
            { name: 'Tuxum', amount: '2 dona' },
            { name: "Tuz, murch, zira, kashnich urug'i va soya sousi.", amount: '' },
        ],
        steps: [
            "Go'shtni qovurish: Qozonda yog'ni qizdirib, go'shtni baland olovda qizarguncha qovuring.",
            "Sabzavotlar: Piyozni solib, pomidor va sarimsoqni qo'shing. Bulg'or qalampirini solib, 2-3 daqiqa qovuring.",
            "Xamirni qo'shish: Oldindan pishirilgan xamirni qozonga soling. Soya sousi va ziravorlarni qo'shing.",
            "Qovurish: Barcha masalliqlarni baland olovda 5 daqiqa aralashtirib qovuring.",
            "Tuxum: Alohida tavada pishirilgan tuxumli quymoqni somoncha to'g'rab, oxirida qo'shib yuboring.",
            "Taomni keng likopchaga solib, ko'k piyoz va kashnich sepib torting.",
        ],
    },
    // ===== GAZAKLAR =====
    'Achiq-chuchuk': {
        ingredients: [
            { name: 'Pomidor', amount: '3-4 dona' },
            { name: 'Piyoz', amount: '1 dona' },
            { name: 'Achchiq qalampir', amount: 'Yarimta' },
            { name: 'Rayhon', amount: 'Bir necha barg' },
            { name: 'Tuz', amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Piyoz: Piyozni yupqa, parrak-parrak qilib to'g'rang. Sovuq suvda chayib olsangiz, achchig'i ketadi.",
            "Pomidor: Pomidorni juda yupqa, tilim-tilim qilib to'g'rang.",
            "Qalampir: Achchiq qalampirni mayda parrak qilib qo'shing.",
            "Aralashtirish: Tuzni dasturxonga tortishdan oldin seping.",
            "Rayhon: Yangi rayhon barglarini qo'lda bo'laklab qo'shing.",
        ],
    },
    'Svejiy salat': {
        ingredients: [
            { name: 'Pomidor', amount: '3-4 dona' },
            { name: 'Bodring', amount: '2 dona' },
            { name: "Bulg'or qalampiri", amount: '1 dona' },
            { name: 'Qizil piyoz', amount: '1 dona' },
            { name: "Zaytun yog'i", amount: '2-3 osh qoshiq' },
            { name: 'Limon suvi', amount: '1 choy qoshiq' },
            { name: "Rayhon, kashnich va ukrop", amount: '' },
            { name: 'Tuz va murch', amount: '' },
        ],
        steps: [
            "Sabzavotlarni to'g'rash: Pomidor va bodringni kubik shaklida to'g'rang.",
            "Piyoz va qalampir: Piyozni yupqa yarim halqa, bulg'or qalampirini somoncha shaklida to'g'rang.",
            "Ko'katlar: Rayhon barglarini qo'lda bo'laklang, qolganlarni mayda to'g'rang.",
            "Zalivka: Yog', limon suvi, tuz va murchni aralashtiring.",
            "Aralashtirish: Hamma masalliqlarni idishga solib, sousni quyib aralashtiring.",
        ],
    },
    'Olivia': {
        ingredients: [
            { name: 'Kartoshka (pishirilgan)', amount: '3-4 dona' },
            { name: "Qaynatilgan go'sht yoki kolbasa", amount: '300 gr' },
            { name: 'Tuxum (qaynatilgan)', amount: '3-4 dona' },
            { name: 'Tuzlangan bodring', amount: '3-4 dona' },
            { name: "Konservalangan ko'k no'xat", amount: '200 gr' },
            { name: 'Sabzi (pishirilgan)', amount: '2 dona' },
            { name: 'Mayonez', amount: '150-200 gr' },
            { name: 'Tuz', amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Qaynatish: Kartoshka, sabzi va tuxumni pishguncha qaynatib oling. Sovugach, po'stini arching.",
            "To'g'rash: Hamma masalliqlarni bir xil kattalikdagi mayda kubik shaklda to'g'rang.",
            "Aralashtirish: To'g'ralgan masalliqlarni katta idishga solib, no'xatni qo'shing.",
            "Mayonez va tuz qo'shib yaxshilab aralashtiring. Sovutgichda 30 daqiqa tindiring.",
        ],
    },
    'Tovuqli sezar': {
        ingredients: [
            { name: 'Tovuq filesi', amount: '300-400 g' },
            { name: 'Ayberg salat bargi', amount: '1 dona' },
            { name: 'Cherri pomidori', amount: '11-12 dona' },
            { name: 'Pishloq (Parmezan)', amount: '50-70 gr' },
            { name: 'Suxariklar', amount: '100 gr' },
            { section: 'Sezar sousi (Eng muhim qismi)' },
            { name: 'Mayonez', amount: '150 gr' },
            { name: 'Limon suvi', amount: '1 choy qoshiq' },
            { name: 'Xantal (Gorchitsa)', amount: '1 choy qoshiq' },
            { name: 'Soya sousi', amount: '1 choy qoshiq' },
        ],
        steps: [
            "Tovuq: Fileni ziravorlar sepib, tovada tillarang bo'lguncha qovuring. Sovugach, parrak to'g'rang.",
            "Suxariklar: Oq nonni kubik to'g'rab, sariyog' va sarimsoq bilan qarsildoq bo'lguncha qizartiring.",
            "Salat bargi: Aybergni qo'l bilan yirikroq bo'laklarga bo'ling.",
            "Jamlash: Keng likopchaga salat barglarini qo'ying. Ustidan sousning yarmini quying.",
            "Bezatish: Ustiga tovuq, cherri pomidorlari va suxariklarni tizing.",
            "Yakun: Qolgan sousni quyib, yupqa tilimlangan Parmezan pishloqni seping.",
        ],
    },
    'Suzma salat': {
        ingredients: [
            { name: 'Pomidor', amount: '1 dona' },
            { name: 'Rediska', amount: '4 dona' },
            { name: 'Bodring', amount: '1 dona' },
            { name: 'Ukrop, kashnich va sarimsoq', amount: '' },
            { name: 'Tuz va murch', amount: '' },
        ],
        steps: [
            "Pomidorni kichik bo'laklarga to'g'rang.",
            "Rediska va bodringni yarim oy shaklida to'g'rab, idishga soling.",
            "Ko'katlarni mayda qilib to'g'rab, barcha sabzavotlar bilan aralashtiring.",
            "Ustidan suzmani solib, yaxshilab aralashtiring.",
            "Ta'bga ko'ra tuz va murch soling.",
        ],
    },
    'Toshkent': {
        ingredients: [
            { name: 'Daikon turpi (yoki oddiy)', amount: '150 gr' },
            { name: "Qaynatilgan Go'sht", amount: '400 gr' },
            { name: 'Mayonez-Smetana', amount: '40 gr dan' },
            { name: 'Qovurilgan piyoz (fri)', amount: '20 gr' },
            { name: 'Bedana tuxumi', amount: '2 dona' },
            { name: 'Korn salat bargi (mini)', amount: '1-2 dona' },
            { name: "Ko'k piyoz", amount: '1 gr' },
        ],
        steps: [
            "Daikon: Turpni juda ingichka somoncha shaklida to'g'rang.",
            "Go'sht: Qaynatilgan buzoq go'shtini tolalari bo'ylab ingichka tasmalar qilib to'g'rang.",
            "Piyoz: Piyozni yupqa yarim halqa qilib, tillarang bo'lguncha frityurda qovuring.",
            "Aralashtirish: Idishda daikon, go'sht va qovurilgan piyozni mayonez bilan aralashtiring.",
            "Bezatish: Massani likopchaga gorka qilib soling. Bedana tuxumlari va ko'katlar bilan bezang.",
        ],
    },
    'Qarsildoq Baqlajon': {
        ingredients: [
            { name: 'Baqlajon', amount: '2 dona (500 gr)' },
            { name: 'Pomidor', amount: '2-3 dona (250 gr)' },
            { name: "Bulg'or qalampiri", amount: '1 dona' },
            { name: "Jo'xori kraxmali", amount: '100 gr' },
            { name: "O'simlik yog'i", amount: '300 ml' },
            { name: "Kinzaning yangi barglari", amount: "yarim bog'" },
            { name: 'Kunjut', amount: '1 choy qoshiq' },
            { name: 'Tuz va murch', amount: '' },
            { section: 'Sous uchun' },
            { name: 'Svit chili sousi', amount: '3-4 osh qoshiq' },
            { name: 'Soya sousi', amount: '1 osh qoshiq' },
            { name: 'Sarimsoqpiyoz', amount: '2 dona' },
            { name: 'Limon suvi', amount: '1 osh qoshiq' },
        ],
        steps: [
            "Baqlajonlarni to'g'rash: Po'stini archmasdan, yirik uchburchak yoki kubik shaklida to'g'rang.",
            "Kraxmallash: Baqlajonlarni bir oz namlab, mo'l-ko'l kraxmalga belab oling.",
            "Qovurish: Tavada yog'ni qizdiring. Baqlajonlarni baland olovda tillarang va qarsildoq bo'lguncha 3-5 daqiqa qovuring.",
            "Yog'ini olish: Qovurilgan baqlajonlarni qog'oz salfetka ustiga oling.",
            "Sabzavotlarni tayyorlash: Pomidor va qalampirini yirik bo'laklarga bo'ling. Kinzani yirikroq to'g'rang.",
            "Sousni aralashtirish: Svit chili sousi, soya sousi, sarimsoq va limon suvini aralashtiring.",
            "Jamlash: Baqlajonlarni, sabzavotlarni sous bilan aralashtiring. Darhol dasturxonga torting.",
        ],
    },
    'Vinegret': {
        ingredients: [
            { name: 'Lavlagi (pishirilgan)', amount: '300-400 gr' },
            { name: 'Kartoshka (pishirilgan)', amount: '300 gr' },
            { name: 'Sabzi (pishirilgan)', amount: '150-200 gr' },
            { name: 'Tuzlangan bodring', amount: '200 gr' },
            { name: 'Konservalangan yashil noxot', amount: '200 gr' },
            { name: "Piyoz (xohishga ko'ra)", amount: '1 dona' },
            { name: "O'simlik yog'i", amount: '3-4 osh qoshiq' },
            { name: 'Tuz va murch', amount: '' },
        ],
        steps: [
            "Sabzavotlarni pishirish: Lavlagi, kartoshka va sabzini yumshaguncha qaynatib oling.",
            "To'g'rash: Sovutilgan sabzavotlar va bodringni kichik kubik shaklida to'g'rang.",
            "Aralashtirish: To'g'ralgan masalliqlarni katta idishga solib, yashil noxotni qo'shing.",
            "Ziravorlar: Tuz, murch va yog'ni qo'shib, yaxshilab aralashtiring.",
        ],
    },
    'Horovatz': {
        ingredients: [
            { name: 'Baqlajon', amount: '2 dona' },
            { name: "Bulg'or qalampiri", amount: '3-4 dona' },
            { name: 'Pomidor', amount: '3 dona' },
            { name: 'Achchiq qalampir', amount: 'yarimta' },
            { name: 'Qizil piyoz', amount: '1 dona (kichikroq)' },
            { name: 'Sarimsoqpiyoz', amount: '2-3 dona' },
            { name: "Zaytun yog'i", amount: '3-4 osh qoshiq' },
            { name: 'Rayhon va kashnich', amount: "1 bog'dan" },
        ],
        steps: [
            "Pishirish: Baqlajon, bulg'or qalampiri va pomidorlarni butunligicha olovda po'sti qorayib pishirib oling.",
            "Tozalash: Pishgan sabzavotlarni sovuq suvga botirib, po'stini arching. Urug'laridan tozalang.",
            "To'g'rash: Sabzavotlarni yirikroq kubik yoki somoncha shaklida to'g'rang.",
            "To'g'ralgan sabzavotlarni blender yoki myasorubkada bir marta chiqaring.",
            "Murch, limon sharbati va zaytun yog'ini quyib, qizil piyoz va ko'katlar bilan bezating.",
        ],
    },
    'Lazzat': {
        ingredients: [
            { name: "Buzoq go'shti (telyatina)", amount: '200-250 gr' },
            { name: 'Bodring', amount: '2 dona' },
            { name: 'Piyoz (oq yoki qizil)', amount: '1 dona' },
            { name: 'Yashil piyoz va kashnich', amount: "yarim bog'" },
            { name: 'Sarimsoqpiyoz', amount: '1-2 dona' },
            { section: 'Sous uchun' },
            { name: 'Soya sousi', amount: '2 osh qoshiq' },
            { name: 'Pomidor pastasi yoki tomat sousi', amount: '1 osh qoshiq' },
            { name: "O'simlik yog'i (qovurish uchun)", amount: '' },
            { name: 'Kunjut (bezatish uchun)', amount: '' },
            { name: 'Tuz, murch va ziravorlar', amount: '' },
        ],
        steps: [
            "Go'shtni tayyorlash: Buzoq go'shtini ingichka somoncha shaklida to'g'rang. Tovada qizigan yog'da baland olovda qovuring.",
            "Sous bilan pishirish: Piyozni qo'shing. Pomidor pastasi, soya sousi va sarimsoqni solib, 5-7 daqiqa dimlang.",
            "Sabzavotlarni to'g'rash: Bodringlarni ingichka somoncha shaklida to'g'rang. Ko'katlarni ham maydalang.",
            "Aralashtirish: Yangi bodringlar, ko'katlar va go'shtli aralashmani birlashtiring.",
            "Yakuniy qism: Hammasini aralashtrib, ustidan kunjut seping.",
        ],
    },
    'Amerikanskiy': {
        ingredients: [
            { name: 'Dudlangan tovuq (grudinka)', amount: '200-250 gr' },
            { name: "Qo'ziqorin (shampinyon)", amount: '200 gr' },
            { name: 'Tuzlangan bodring', amount: '2-3 dona' },
            { name: "Konservalangan jo'xori", amount: 'yarim banka' },
            { name: 'Tuxum (qaynatilgan)', amount: '3-4 dona' },
            { name: 'Salat bargi', amount: "yarim bog'" },
            { name: 'Mayonez', amount: '' },
            { name: 'Tuz va murch', amount: '' },
        ],
        steps: [
            "To'g'rash: Dudlangan tovuq va bodringni kubik shaklida to'g'rang.",
            "Qo'ziqorin va jo'xori: Qo'ziqorinlarni bo'laklarga bo'ling. Jo'xorini qo'shing.",
            "Tuxum va salat bargi: Tuxumlarni to'rtburchak to'g'rang. Salat barglarini qo'l bilan bo'laklarga bo'ling.",
            "Aralashtirish: Barcha masalliqlarni bitta idishga solib, tuz, murch va mayonez qo'shib aralashtiring.",
        ],
    },
    'Fransuzkiy': {
        ingredients: [
            { name: "Go'sht (qaynatilgan)", amount: '200-250 gr' },
            { name: 'Lavlagi (pishirilgan)', amount: '200 gr' },
            { name: 'Kartoshka (pay uchun)', amount: '300 gr' },
            { name: 'Karam', amount: '150 gr' },
            { name: 'Tuxum (qaynatilgan)', amount: '2-3 dona' },
            { name: 'Bodring (tuzlangan)', amount: '2 dona' },
            { name: 'Mayonez', amount: '3-4 osh qoshiq' },
            { name: 'Tuz, murch', amount: "Ta'bga ko'ra" },
        ],
        steps: [
            "Kartoshkani tayyorlash: Kartoshkani ingichka somoncha qilib to'g'rang, yuvib kraxmalini chiqaring. Mo'l yog'da tillarang bo'lguncha qovuring.",
            "Masalliqlarni to'g'rash: Go'sht, lavlagi, bodring, tuxum va karamni ingichka somoncha shaklida to'g'rang.",
            "Aralashtirish: Masalliqlarni idishga solib, mayonez va ziravorlar bilan aralashtiring.",
        ],
    },
    'Grekcha salat': {
        ingredients: [
            { name: 'Pomidor', amount: '300 gr' },
            { name: 'Bodring', amount: '300 gr' },
            { name: "Bulg'or qalampir", amount: '1 dona' },
            { name: "Feta pishlog'i", amount: '200 gr' },
            { name: 'Qizil piyoz', amount: '50 gr' },
            { name: 'Qora zaytun', amount: '100 gr' },
            { name: 'Zaytun moyi', amount: '3-4 osh qoshiq' },
            { name: 'Limon sharbati', amount: '1 osh qoshiq' },
            { name: 'Quritilgan oregano', amount: '1 choy qoshiq' },
        ],
        steps: [
            "Sabzavotlarni to'g'rash: Pomidorlarni to'rtga bo'ling. Bodringni yirik to'rtburchak qilib to'g'rang.",
            "Qalampir va piyoz: Bulg'or qalampirini yirik bo'laklarga, piyozni yupqa yarim halqa shaklida to'g'rang.",
            "Sous tayyorlash: Zaytun moyi, limon sharbati, tuz, murch va oreganoni aralashtiring.",
            "Aralashtirish: To'g'ralgan sabzavotlarni va zaytunni katta idishga solib, sous bilan aralashtiring.",
            "Pishloqni qo'shish: Eng oxirida pishloqni yirik kubik qilib to'g'rab salat ustiga qo'ying.",
        ],
    },
    'Kapriz': {
        ingredients: [
            { name: "Qaynatilgan mol go'shti", amount: '150-200 gr' },
            { name: 'Dudlangan kolbasa', amount: '100-150 gr' },
            { name: "Dudlangan kurka go'shti", amount: '100-150 gr' },
            { name: "Qazi (xohishga ko'ra)", amount: '100-150 gr' },
            { name: 'Qattiq pishloq', amount: '100-150 gr' },
            { name: 'Tuzlangan bodring', amount: '3-4 dona' },
            { name: 'Mayonez', amount: '4-5 osh qoshiq' },
            { name: "Konservalangan makkajo'xori", amount: 'yarim banka' },
        ],
        steps: [
            "Barcha go'sht mahsulotlari va pishloqni ingichka somoncha shaklida to'g'rang.",
            "Bodringni ham somoncha qilib to'g'rang.",
            "Katta idishda to'g'ralgan masalliqlarni makkajo'xori bilan aralashtiring.",
            "Mayonez qo'shib, murch seping.",
        ],
    },
    'Humus': {
        ingredients: [
            { name: "Nut (no'xat)", amount: '200-250 gr' },
            { name: 'Tahini (kunchut pastasi)', amount: '100-120 gr' },
            { name: 'Limon sharbati', amount: '1-2 dona' },
            { name: 'Zaytun moyi', amount: '2-3 osh qoshiq' },
            { name: 'Sarimsoq piyoz', amount: '2-3 dona' },
            { name: 'Muzdek suv', amount: '2-3 osh qoshiq' },
            { name: "Tuz tabga ko'ra", amount: '' },
        ],
        steps: [
            "No'xatni tayyorlash: Quruq no'xatni 8-12 soat suvda ivitib, yumshaguncha qaynatib oling.",
            "Aralashtirish: Blenderga tahini va limon sharbatini solib, oppoq massa hosil bo'lguncha ko'pirtiring.",
            "No'xatni qo'shish: Pishgan no'xatni ikki bo'lib, navbatma-navbat solib maydalang.",
            "Teksturani rostlash: Humus quyuq bo'lsa, muzdek suv qo'shib, kerakli yumshoqlikka keltiring.",
            "Tuz qo'shib, ustiga zaytun moyi quyib torting.",
        ],
    },
};
